### ISSUE TITLE
About page "Loading"

### ISSUE THREAD

**Issue by leggsimon** [jackfranklin/elmplayground#11]
Nice work Jack but I have found, oddly only on the "About" page it really noticeably shows "Loading" for a split second before the content loads

**Comment by jackfranklin** [comment]
Yeah it can occasionally be a bit slow, not sure why. The big fix here is #6, which would mean it's only slow once.

**Comment by leggsimon** [comment]
It seems strange that it only seems to affect the "About" page for me though. The "Home" and "Archives" pages load immediately

**Comment by jackfranklin** [comment]
Both of those pages don't make HTTP reqs because they are special cases: https://github.com/jackfranklin/elmplayground/blob/master/src/ViewSpecialCases.elm

The blog posts + about pages make HTTP reqs.

**Comment by jackfranklin** [comment]
Also the `hasSpecialCase` method there is completely wrong.

**Comment by jackfranklin** [comment]
Fixed the `hasSpecialCase` logic; nothing more to do here.
