### ISSUE TITLE
Posts.elm and Pages.elm should be a config file

### ISSUE THREAD

**Issue by gabrielperales** [jackfranklin/elmplayground#24]
Wouldn't be better have a `config.json` with all those posts and pages there?

**Comment by jackfranklin** [comment]
I like having them encoded into Elm, then they are easy to import and pass around. Wouldn't like the extra complexity of parsing JSON + passing that into the Elm app.

**Comment by gabrielperales** [comment]
I did a version loading the content from that `config.json`, just because I thought it could be fun to do it as I still being a newbie with Elm. If you are curious, you can have a look to it [here](https://github.com/gabrielperales/elmplayground/tree/configjson)
